---
abstract: 'use regexes with file utils like rm, cp, mv, ln'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-RegexFileUtils
requires:
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/plicease/App-RegexFileUtils/issues
  homepage: http://search.cpan.org/dist/App-RegexFileUtils/
  repository: git://github.com/plicease/App-RegexFileUtils.git
version: 0.04
